partial:
  by: target
version: 2
project_name: axoflow-otel-collector-releases
env:
  - COSIGN_YES=true
release:
  disable: "true"
msi:
  - id: axoflow-otel-collector
    name: axoflow-otel-collector_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - config.yaml
builds:
  - id: axoflow-otel-collector
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: axoflow-otel-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: axoflow-otel-collector
    builds:
      - axoflow-otel-collector
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
nfpms:
  - package_name: axoflow-otel-collector
    contents:
      - src: axoflow-otel-collector.service
        dst: /lib/systemd/system/axoflow-otel-collector.service
      - src: axoflow-otel-collector.conf
        dst: /etc/axoflow-otel-collector/axoflow-otel-collector.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/axoflow-otel-collector/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: axoflow-otel-collector
    builds:
      - axoflow-otel-collector
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - axoflow-otel-collector
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_axoflow-otel-collector_checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-arm64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:{{ .Version }}-arm64
  - name_template: ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest
    image_templates:
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-amd64
      - ghcr.io/axoflow/axoflow-otel-collector/axoflow-otel-collector:latest-arm64
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
