partial:
  by: target
project_name: opentelemetry-collector-releases
builds:
    - id: otelcol
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - "386"
        - amd64
        - arm
        - arm64
        - ppc64le
        - s390x
      goarm:
        - "7"
      ignore:
        - goos: darwin
          goarch: "386"
        - goos: darwin
          goarch: arm
        - goos: darwin
          goarch: s390x
        - goos: windows
          goarch: arm
        - goos: windows
          goarch: arm64
        - goos: windows
          goarch: s390x
      dir: distributions/otelcol/_build
      binary: otelcol
      ldflags:
        - -s
        - -w
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
    - id: otelcol-contrib
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - "386"
        - amd64
        - arm
        - arm64
        - ppc64le
        - s390x
      goarm:
        - "7"
      ignore:
        - goos: darwin
          goarch: "386"
        - goos: darwin
          goarch: arm
        - goos: darwin
          goarch: s390x
        - goos: windows
          goarch: arm
        - goos: windows
          goarch: arm64
        - goos: windows
          goarch: s390x
      dir: distributions/otelcol-contrib/_build
      binary: otelcol-contrib
      ldflags:
        - -s
        - -w
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
archives:
    - id: otelcol
      builds:
        - otelcol
      name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    - id: otelcol-contrib
      builds:
        - otelcol-contrib
      name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
    - package_name: otelcol
      contents:
        - src: distributions/otelcol/otelcol.service
          dst: /lib/systemd/system/otelcol.service
        - src: distributions/otelcol/otelcol.conf
          dst: /etc/otelcol/otelcol.conf
          type: config|noreplace
        - src: configs/otelcol.yaml
          dst: /etc/otelcol/config.yaml
          type: config
      scripts:
        preinstall: distributions/otelcol/preinstall.sh
        postinstall: distributions/otelcol/postinstall.sh
        preremove: distributions/otelcol/preremove.sh
      id: otelcol
      builds:
        - otelcol
      formats:
        - apk
        - deb
        - rpm
      maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
      description: OpenTelemetry Collector - otelcol
      license: Apache 2.0
    - package_name: otelcol-contrib
      contents:
        - src: distributions/otelcol-contrib/otelcol-contrib.service
          dst: /lib/systemd/system/otelcol-contrib.service
        - src: distributions/otelcol-contrib/otelcol-contrib.conf
          dst: /etc/otelcol-contrib/otelcol-contrib.conf
          type: config|noreplace
        - src: configs/otelcol-contrib.yaml
          dst: /etc/otelcol-contrib/config.yaml
          type: config
      scripts:
        preinstall: distributions/otelcol-contrib/preinstall.sh
        postinstall: distributions/otelcol-contrib/postinstall.sh
        preremove: distributions/otelcol-contrib/preremove.sh
      id: otelcol-contrib
      builds:
        - otelcol-contrib
      formats:
        - apk
        - deb
        - rpm
      maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
      description: OpenTelemetry Collector - otelcol-contrib
      license: Apache 2.0
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
    - goos: linux
      goarch: "386"
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-386
        - otel/opentelemetry-collector:latest-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-386
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/386
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: amd64
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-amd64
        - otel/opentelemetry-collector:latest-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-amd64
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/amd64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: arm
      goarm: "7"
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-armv7
        - otel/opentelemetry-collector:latest-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-armv7
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/arm/v7
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: arm64
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-arm64
        - otel/opentelemetry-collector:latest-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-arm64
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: ppc64le
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-ppc64le
        - otel/opentelemetry-collector:latest-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-ppc64le
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/ppc64le
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: s390x
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-s390x
        - otel/opentelemetry-collector:latest-s390x
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-s390x
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/s390x
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: "386"
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-386
        - otel/opentelemetry-collector-contrib:latest-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-386
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/386
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: amd64
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-amd64
        - otel/opentelemetry-collector-contrib:latest-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-amd64
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/amd64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: arm
      goarm: "7"
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-armv7
        - otel/opentelemetry-collector-contrib:latest-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-armv7
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/arm/v7
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: arm64
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-arm64
        - otel/opentelemetry-collector-contrib:latest-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-arm64
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: ppc64le
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
        - otel/opentelemetry-collector-contrib:latest-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-ppc64le
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/ppc64le
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
    - goos: linux
      goarch: s390x
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-s390x
        - otel/opentelemetry-collector-contrib:latest-s390x
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-s390x
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-s390x
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/s390x
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
docker_manifests:
    - name_template: otel/opentelemetry-collector:{{ .Version }}
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-386
        - otel/opentelemetry-collector:{{ .Version }}-amd64
        - otel/opentelemetry-collector:{{ .Version }}-armv7
        - otel/opentelemetry-collector:{{ .Version }}-arm64
        - otel/opentelemetry-collector:{{ .Version }}-ppc64le
        - otel/opentelemetry-collector:{{ .Version }}-s390x
    - name_template: otel/opentelemetry-collector:latest
      image_templates:
        - otel/opentelemetry-collector:latest-386
        - otel/opentelemetry-collector:latest-amd64
        - otel/opentelemetry-collector:latest-armv7
        - otel/opentelemetry-collector:latest-arm64
        - otel/opentelemetry-collector:latest-ppc64le
        - otel/opentelemetry-collector:latest-s390x
    - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}
      image_templates:
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
    - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest
      image_templates:
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-s390x
    - name_template: otel/opentelemetry-collector-contrib:{{ .Version }}
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-386
        - otel/opentelemetry-collector-contrib:{{ .Version }}-amd64
        - otel/opentelemetry-collector-contrib:{{ .Version }}-armv7
        - otel/opentelemetry-collector-contrib:{{ .Version }}-arm64
        - otel/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
        - otel/opentelemetry-collector-contrib:{{ .Version }}-s390x
    - name_template: otel/opentelemetry-collector-contrib:latest
      image_templates:
        - otel/opentelemetry-collector-contrib:latest-386
        - otel/opentelemetry-collector-contrib:latest-amd64
        - otel/opentelemetry-collector-contrib:latest-armv7
        - otel/opentelemetry-collector-contrib:latest-arm64
        - otel/opentelemetry-collector-contrib:latest-ppc64le
        - otel/opentelemetry-collector-contrib:latest-s390x
    - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}
      image_templates:
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-s390x
    - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
      image_templates:
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-amd64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-armv7
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-arm64
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-ppc64le
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest-s390x
