project_name: opentelemetry-collector-releases
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - id: "otelcol"
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - "otelcol"
builds:
  - id: "otelcol"
    dir: "distributions/otelcol/_build"
    binary: "otelcol"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - s390x
    goarm:
      - 6
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
docker_manifests:
  - name_template: otel/opentelemetry-collector:{{ .Version }}
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-amd64
      - otel/opentelemetry-collector:{{ .Version }}-armv6
      - otel/opentelemetry-collector:{{ .Version }}-armv7
      - otel/opentelemetry-collector:{{ .Version }}-arm64
dockers:
  - image_templates:
      - "otel/opentelemetry-collector:{{ .Version }}-amd64"
    dockerfile: "distributions/otelcol/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - "configs/otelcol.yaml"
    goarch: amd64
  - image_templates:
      - "otel/opentelemetry-collector:{{ .Version }}-armv6"
    dockerfile: "distributions/otelcol/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    extra_files:
      - "configs/otelcol.yaml"
    goarch: arm
    goarm: 6
  - image_templates:
      - "otel/opentelemetry-collector:{{ .Version }}-armv7"
    dockerfile: "distributions/otelcol/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    extra_files:
      - "configs/otelcol.yaml"
    goarch: arm
    goarm: 7
  - image_templates:
      - "otel/opentelemetry-collector:{{ .Version }}-arm64"
    dockerfile: "distributions/otelcol/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    extra_files:
      - "configs/otelcol.yaml"
    goarch: arm64
nfpms:
  - id: "otelcol"
    package_name: "otelcol"
    license: Apache 2.0
    description: "OpenTelemetry Collector - otelcol"
    formats:
      - apk
      - deb
      - rpm
    scripts:
      preinstall: "distributions/otelcol/preinstall.sh"
      postinstall: "distributions/otelcol/postinstall.sh"
      preremove: "distributions/otelcol/preremove.sh"
    builds:
      - "otelcol"
    contents:
      - src: "distributions/otelcol/otelcol.service"
        dst: "/lib/systemd/system/otelcol.service"
      - src: "distributions/otelcol/otelcol.conf"
        dst: "/etc/otelcol/otelcol.conf"
        type: "config|noreplace"
      - src: "configs/otelcol.yaml"
        dst: "/etc/otelcol/config.yaml"
        type: config
