version: 2
monorepo:
  tag_prefix: cmd/builder/
  dir: .core/cmd/builder
env:
  - CONTAINER_IMAGE_EPHEMERAL_TAG={{ if .IsNightly }}nightly{{ else }}latest{{ end }}
builds:
  - flags:
      - -trimpath
    ldflags:
      - -s -w -X go.opentelemetry.io/collector/cmd/builder/internal.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le
    binary: ocb
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-amd64
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-arm64
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-ppc64le
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
#  - name_template: mowies/opentelemetry-collector-builder:{{ .Version }}
#    image_templates:
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-amd64
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-arm64
#      - mowies/opentelemetry-collector-builder:{{ .Version }}-ppc64le
#  - name_template: mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
#    image_templates:
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
#      - mowies/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
  - name_template: ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}
    image_templates:
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Version }}-ppc64le
  - name_template: ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-builder:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
release:
  make_latest: false
  header: |
    ### Images and binaries for collector distributions here: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/{{ .Tag }}
archives:
  - formats:
    - binary
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  disable: true
signs:
  - if: $SKIP_SIGNS != "true"
    cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - if: $SKIP_SIGNS != "true"
    args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .Now.Format "200601021504" }}'
  tag_name: nightly-builder
  publish_release: true
  keep_single_release: true
