extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  # This section is used to collect the OpenTelemetry Collector metrics
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: ${env:MEMORY_LIMIT_MIB:-512}
  resourcedetection:
    detectors:
      - heroku

exporters:
  otlp:
    endpoint: ${env:OTLP_ENDPOINT}
  #otlphttp:
  #  endpoint: ${env:OTLP_HTTP_ENDPOINT}

  # Debug. Add this to the pipeline you want to debug.
  logging:
    loglevel: debug

service:
  extensions:
    - health_check
    - zpages
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors:
        - memory_limiter
        - batch
        - resourcedetection
      exporters:
        - otlp
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
        - resourcedetection
      exporters:
        - otlp
    metrics/internal:
      receivers:
        - prometheus/internal
      processors:
        - memory_limiter
        - batch
        - resourcedetection
      exporters:
        - otlp
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlp