version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - CGO_ENABLED=0
  - BUILD_FLAGS=-trimpath
msi:
  - id: otelcol-gateway
    name: otelcol-gateway_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
      - config.yaml
builds:
  - id: otelcol-gateway-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-gateway
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-gateway-linux_{{ .Target }}/otelcol-gateway
  - id: otelcol-gateway-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-gateway
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-gateway-darwin_{{ .Target }}/otelcol-gateway
  - id: otelcol-gateway-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
      - ppc64le
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-gateway
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-gateway-windows_{{ .Target }}/otelcol-gateway.exe
archives:
  - id: otelcol-gateway
    builds:
      - otelcol-gateway-linux
      - otelcol-gateway-darwin
      - otelcol-gateway-windows
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol-gateway
    contents:
      - src: otelcol-gateway.service
        dst: /lib/systemd/system/otelcol-gateway.service
      - src: otelcol-gateway.conf
        dst: /etc/otelcol-gateway/otelcol-gateway.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol-gateway/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol-gateway
    builds:
      - otelcol-gateway-linux
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol-gateway
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-gateway_checksums.txt'
dockers:
  - goos: linux
    goarch: "386"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-386
      - otel/opentelemetry-collector-gateway:latest-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-386
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-amd64
      - otel/opentelemetry-collector-gateway:latest-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-armv7
      - otel/opentelemetry-collector-gateway:latest-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-armv7
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-arm64
      - otel/opentelemetry-collector-gateway:latest-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector-gateway:latest-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-ppc64le
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-s390x
      - otel/opentelemetry-collector-gateway:latest-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-s390x
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: otel/opentelemetry-collector-gateway:{{ .Version }}
    image_templates:
      - otel/opentelemetry-collector-gateway:{{ .Version }}-386
      - otel/opentelemetry-collector-gateway:{{ .Version }}-amd64
      - otel/opentelemetry-collector-gateway:{{ .Version }}-armv7
      - otel/opentelemetry-collector-gateway:{{ .Version }}-arm64
      - otel/opentelemetry-collector-gateway:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector-gateway:{{ .Version }}-s390x
  - name_template: otel/opentelemetry-collector-gateway:latest
    image_templates:
      - otel/opentelemetry-collector-gateway:latest-386
      - otel/opentelemetry-collector-gateway:latest-amd64
      - otel/opentelemetry-collector-gateway:latest-armv7
      - otel/opentelemetry-collector-gateway:latest-arm64
      - otel/opentelemetry-collector-gateway:latest-ppc64le
      - otel/opentelemetry-collector-gateway:latest-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:{{ .Version }}-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-gateway:latest-s390x
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
