# A debian image with systemd enabled.  Must be run with:
# `-d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro` flags
FROM debian:13@sha256:f0b609fc09804b3e800e1357f6d8d6a7467ea8a93da2885206afee62034694e2

ENV container=docker \
    DEBIAN_FRONTEND=noninteractive

# Enable systemd.
RUN apt-get update ; \
    apt-get install -y systemd systemd-sysv procps; \
    apt-get clean ; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d

CMD ["/lib/systemd/systemd"]
