version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w -X github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/internal.version={{ .Version }}
  - BUILD_FLAGS=-trimpath
  - CONTAINER_IMAGE_EPHEMERAL_TAG={{ if .IsNightly }}nightly{{ else }}latest{{ end }}
  - GOPROXY=https://proxy.golang.org,direct
  - CGO_ENABLED=0
release:
  github:
    owner: open-telemetry
    name: opentelemetry-collector-releases
  make_latest: "false"
  header: '### Release of OpAMP supervisor artifacts'
builds:
  - id: opampsupervisor-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
    binary: opampsupervisor
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: opampsupervisor-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: opampsupervisor
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: opampsupervisor-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: opampsupervisor
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
archives:
  - formats:
      - binary
snapshot:
  version_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-amd64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-arm64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: otel/opentelemetry-collector-opampsupervisor:{{ .Version }}
    image_templates:
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-amd64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-arm64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Version }}-ppc64le
  - name_template: otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - otel/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Version }}-ppc64le
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
changelog:
  disable: "true"
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    if: $SKIP_SIGNS != 'true'
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
    if: $SKIP_SIGNS != 'true'
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: cmd/opampsupervisor/
  dir: .contrib/cmd/opampsupervisor
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .ShortCommit }}'
  tag_name: nightly-opampsupervisor
  keep_single_release: true
