partial:
  by: target
version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
msi:
  - id: otelcol-minimal
    name: otelcol-minimal_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
builds:
  - id: otelcol-minimal
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol-minimal
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: otelcol-minimal
    builds:
      - otelcol-minimal
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol-minimal
    contents:
      - src: otelcol-minimal.service
        dst: /lib/systemd/system/otelcol-minimal.service
      - src: otelcol-minimal.conf
        dst: /etc/otelcol-minimal/otelcol-minimal.conf
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol-minimal
    builds:
      - otelcol-minimal
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol-minimal
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-minimal_checksums.txt'
dockers:
  - goos: linux
    goarch: "386"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-386
      - otel/opentelemetry-collector-minimal:latest-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-386
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-amd64
      - otel/opentelemetry-collector-minimal:latest-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-armv7
      - otel/opentelemetry-collector-minimal:latest-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-armv7
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-arm64
      - otel/opentelemetry-collector-minimal:latest-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector-minimal:latest-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-ppc64le
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-s390x
      - otel/opentelemetry-collector-minimal:latest-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-s390x
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: otel/opentelemetry-collector-minimal:{{ .Version }}
    image_templates:
      - otel/opentelemetry-collector-minimal:{{ .Version }}-386
      - otel/opentelemetry-collector-minimal:{{ .Version }}-amd64
      - otel/opentelemetry-collector-minimal:{{ .Version }}-armv7
      - otel/opentelemetry-collector-minimal:{{ .Version }}-arm64
      - otel/opentelemetry-collector-minimal:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector-minimal:{{ .Version }}-s390x
  - name_template: otel/opentelemetry-collector-minimal:latest
    image_templates:
      - otel/opentelemetry-collector-minimal:latest-386
      - otel/opentelemetry-collector-minimal:latest-amd64
      - otel/opentelemetry-collector-minimal:latest-armv7
      - otel/opentelemetry-collector-minimal:latest-arm64
      - otel/opentelemetry-collector-minimal:latest-ppc64le
      - otel/opentelemetry-collector-minimal:latest-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:{{ .Version }}-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-minimal:latest-s390x
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
