version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - BUILD_FLAGS=-trimpath
  - CONTAINER_IMAGE_EPHEMERAL_TAG={{ if .IsNightly }}nightly{{ else }}latest{{ end }}
  - CGO_ENABLED=0
release:
  replace_existing_artifacts: true
msi:
  - id: otelcol-contrib
    name: otelcol-contrib_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
      - config.yaml
builds:
  - id: otelcol-contrib-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-contrib
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-contrib-linux_{{ .Target }}/otelcol-contrib
  - id: otelcol-contrib-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-contrib
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-contrib-darwin_{{ .Target }}/otelcol-contrib
  - id: otelcol-contrib-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol-contrib
    builder: prebuilt
    prebuilt:
      path: artifacts/otelcol-contrib-windows_{{ .Target }}/otelcol-contrib.exe
archives:
  - id: otelcol-contrib
    builds:
      - otelcol-contrib-linux
      - otelcol-contrib-darwin
      - otelcol-contrib-windows
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol-contrib
    contents:
      - src: otelcol-contrib.service
        dst: /lib/systemd/system/otelcol-contrib.service
      - src: otelcol-contrib.conf
        dst: /etc/otelcol-contrib/otelcol-contrib.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol-contrib/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol-contrib
    builds:
      - otelcol-contrib-linux
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol-contrib
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-contrib_checksums.txt'
dockers:
  - goos: linux
    goarch: "386"
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-386
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-386
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-armv7
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-armv7
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-arm64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-s390x
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-s390x
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: windows
    goarch: amd64
    dockerfile: Windows.dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-windows-2019-amd64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2019-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-windows-2019-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2019-amd64
    skip_build: '{{ not (eq .Runtime.Goos "windows") }}'
    skip_push: '{{ not (eq .Runtime.Goos "windows") }}'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --build-arg=WIN_VERSION=2019
      - --platform=windows/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: docker
  - goos: windows
    goarch: amd64
    dockerfile: Windows.dockerfile
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-windows-2022-amd64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2022-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-windows-2022-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2022-amd64
    skip_build: '{{ not (eq .Runtime.Goos "windows") }}'
    skip_push: '{{ not (eq .Runtime.Goos "windows") }}'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --build-arg=WIN_VERSION=2022
      - --platform=windows/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: docker
docker_manifests:
  - name_template: mowies/opentelemetry-collector-contrib:{{ .Version }}
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-386
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-armv7
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-arm64
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
      - mowies/opentelemetry-collector-contrib:{{ .Version }}-s390x
  - name_template: mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - mowies/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
  - name_template: ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}
    image_templates:
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-386
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-armv7
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Version }}-s390x
  - name_template: ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/mowies/opentelemetry-collector-releases/opentelemetry-collector-contrib:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .Now.Format "200601021504" }}'
  tag_name: nightly
  publish_release: true
  keep_single_release: true
