partial:
  by: target
version: 2
project_name: opentelemetry-collector-releases
builds:
  - id: otelcol-contrib-pie
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: linux
        goarch: "386"
      - goos: linux
        goarch: arm
      - goos: linux
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
      - -buildmode=pie
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
  - id: otelcol-contrib
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: s390x
      - goos: linux
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: linux
        goarch: ppc64le
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: amd64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
monorepo:
  tag_prefix: v
