version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - BUILD_FLAGS=-trimpath
  - CONTAINER_IMAGE_EPHEMERAL_TAG={{ if .IsNightly }}nightly{{ else }}latest{{ end }}
  - GOPROXY=https://proxy.golang.org,direct
  - CGO_ENABLED=0
release:
  replace_existing_artifacts: true
msi:
  - id: otelcol
    name: otelcol_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
      - config.yaml
builds:
  - id: otelcol-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
archives:
  - id: otelcol
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    builds:
      - otelcol-linux
      - otelcol-darwin
      - otelcol-windows
nfpms:
  - package_name: otelcol
    contents:
      - src: otelcol.service
        dst: /lib/systemd/system/otelcol.service
      - src: otelcol.conf
        dst: /etc/otelcol/otelcol.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol
    license: Apache 2.0
    builds:
      - otelcol-linux
checksum:
  name_template: '{{ .ProjectName }}_otelcol{{ if eq .Runtime.Goos "windows" }}_{{ .Runtime.Goos }}{{ end }}_checksums.txt'
dockers:
  - goos: linux
    goarch: "386"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-386
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-amd64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-armv7
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-arm64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: riscv64
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-riscv64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-riscv64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-riscv64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-riscv64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/riscv64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-s390x
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: windows
    goarch: amd64
    dockerfile: Windows.dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-windows-2019-amd64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2019-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-windows-2019-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2019-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --build-arg=WIN_VERSION=2019
      - --platform=windows/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: docker
  - goos: windows
    goarch: amd64
    dockerfile: Windows.dockerfile
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-windows-2022-amd64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2022-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-windows-2022-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2022-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --build-arg=WIN_VERSION=2022
      - --platform=windows/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: docker
docker_manifests:
  - name_template: otel/opentelemetry-collector:{{ .Version }}
    image_templates:
      - otel/opentelemetry-collector:{{ .Version }}-386
      - otel/opentelemetry-collector:{{ .Version }}-amd64
      - otel/opentelemetry-collector:{{ .Version }}-armv7
      - otel/opentelemetry-collector:{{ .Version }}-arm64
      - otel/opentelemetry-collector:{{ .Version }}-ppc64le
      - otel/opentelemetry-collector:{{ .Version }}-riscv64
      - otel/opentelemetry-collector:{{ .Version }}-s390x
  - name_template: otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-riscv64
      - otel/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-riscv64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
  - name_template: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}
    image_templates:
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-386
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-amd64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-armv7
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-arm64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-ppc64le
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-riscv64
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-s390x
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .ShortCommit }}'
  tag_name: nightly-otelcol
  keep_single_release: true
