version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - BUILD_FLAGS=-trimpath
  - CGO_ENABLED=0
release:
  replace_existing_artifacts: true
msi:
  - id: otelcol
    name: otelcol_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
      - config.yaml
builds:
  - id: otelcol-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
archives:
  - id: otelcol
    builds:
      - otelcol-linux
      - otelcol-darwin
      - otelcol-windows
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol
    contents:
      - src: otelcol.service
        dst: /lib/systemd/system/otelcol.service
      - src: otelcol.conf
        dst: /etc/otelcol/otelcol.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol
    builds:
      - otelcol-linux
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol_checksums.txt'
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .Now.Format "200601021504" }}'
  tag_name: nightly
  publish_release: true
