version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - BUILD_FLAGS=-trimpath
  - CONTAINER_IMAGE_EPHEMERAL_TAG={{ if .IsNightly }}nightly{{ else }}latest{{ end }}
  - GOPROXY=https://proxy.golang.org,direct
  - CGO_ENABLED=0
release:
  replace_existing_artifacts: true
msi:
  - id: otelcol
    name: otelcol_{{ .Version }}_{{ .Os }}_{{ .MsiArch }}
    wxs: windows-installer.wxs
    extra_files:
      - opentelemetry.ico
      - config.yaml
builds:
  - id: otelcol-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "7"
    goppc64:
      - power8
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
  - id: otelcol-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    dir: _build
    binary: otelcol
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
archives:
  - id: otelcol
    ids:
      - otelcol-linux
      - otelcol-darwin
      - otelcol-windows
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol
    contents:
      - src: otelcol.service
        dst: /lib/systemd/system/otelcol.service
      - src: otelcol.conf
        dst: /etc/otelcol/otelcol.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol/config.yaml
        type: config|noreplace
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: otelcol
    ids:
      - otelcol-linux
    formats:
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol{{ if eq .Runtime.Goos "windows" }}_{{ .Runtime.Goos }}{{ end }}_checksums.txt'
dockers_v2:
  - dockerfile: Dockerfile
    ids:
      - otelcol-linux
    extra_files:
      - config.yaml
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/386
      - linux/arm/v7
      - linux/ppc64le
      - linux/riscv64
      - linux/s390x
    images:
      - otel/opentelemetry-collector
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector
    tags:
      - "{{ .Version }}"
      - "{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    flags:
      - "--pull"
  - dockerfile: Windows.dockerfile
    ids:
      - otelcol-windows
    extra_files:
      - config.yaml
    platforms:
      - windows/amd64
    images:
      - otel/opentelemetry-collector
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector
    tags:
      - "{{ .Version }}-windows-2019"
      - "{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2019"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    flags:
      - "--pull"
    build_args:
      WIN_VERSION: "2019"
  - dockerfile: Windows.dockerfile
    ids:
      - otelcol-windows
    extra_files:
      - config.yaml
    platforms:
      - windows/amd64
    images:
      - otel/opentelemetry-collector
      - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector
    tags:
      - "{{ .Version }}-windows-2022"
      - "{{ .Env.CONTAINER_IMAGE_EPHEMERAL_TAG }}-windows-2022"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    flags:
      - "--pull"
    build_args:
      WIN_VERSION: "2022"
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
monorepo:
  tag_prefix: v
partial:
  by: target
nightly:
  version_template: '{{ incpatch .Version}}-nightly.{{ .ShortCommit }}'
  tag_name: nightly-otelcol
  keep_single_release: true
