name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
      - release/*
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    if: github.event_name != 'merge_group'
    permissions:
      contents: read
      pull-requests: read
    uses:  open-telemetry/shared-workflows/.github/workflows/chloggen.yml@ad1959372f2919fcf2556d3a3d12ed5265c54209
