name: Continuous Integration - Contrib - GoReleaser

on:
  push:
    branches: [main]
    paths:
      - "distributions/otelcol-contrib-cgo/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "distributions/otelcol-contrib-cgo/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"

jobs:
  check-goreleaser:
    name: Continuous Integration - Contrib CGO - GoReleaser
    uses: ./.github/workflows/base-ci-goreleaser.yaml
    with:
      distribution: otelcol-contrib-cgo
      goos: '[ "darwin" ]'
      goarch: '[ "amd64", "arm64" ]'
      runs-on: '[ macos-latest ]'
    secrets: inherit
