name: CI - eBPF Profiler - GoReleaser

on:
  merge_group:
  push:
    branches: [main]
    paths:
      - "distributions/otelcol-ebpf-profiler/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "distributions/otelcol-ebpf-profiler/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  check-goreleaser:
    name: CI - eBPF Profiler - GoReleaser
    uses: ./.github/workflows/base-ci-goreleaser.yaml
    with:
      distribution: otelcol-ebpf-profiler
      config_file: ebpf-profiler-config.yaml
      docker_run_options: '--privileged --pid=host -v /sys/kernel/debug/:/sys/kernel/debug/:ro'
      otelcol_run_options: '--feature-gates=service.profilesSupport'
      goos: '[ "linux" ]'
      goarch: '[ "amd64" ]'
    secrets: inherit
