name: Release OTLP

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  release:
    name: Release OTLP
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-otlp
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x" ]'
      nightly: ${{ contains(github.ref, '-nightly') }}
    secrets: inherit
    permissions: write-all
  release-windows:
    name: Release OTLP (Windows)
    if: ${{ !contains(github.ref, '-nightly') }}
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-otlp
      goos: '[ "windows" ]'
      goarch: '[ "386", "amd64" ]'
      runner_os: windows-2022
    secrets: inherit
    permissions: write-all
