name: Release Builder

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  release:
    name: Release Builder
    uses: ./.github/workflows/base-binary-release.yaml
    with:
      binary: builder
      collector-dependency: 'open-telemetry/opentelemetry-collector'
      dependency-target-folder: '.core'
    secrets:
      DOCKER_TOKEN_COLLECTOR_RELEASES: ${{ secrets.DOCKER_TOKEN_COLLECTOR_RELEASES }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    permissions:
      contents: write
      id-token: write
      packages: write
