name: Release Core

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  release:
    name: Release Core
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x", "riscv64" ]'
      nightly: ${{ contains(github.ref, '-nightly') }}
    secrets:
      DOCKER_TOKEN_COLLECTOR_RELEASES: ${{ secrets.DOCKER_TOKEN_COLLECTOR_RELEASES }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
  release-aix:
    name: Release Core (AIX)
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol
      goos: '[ "aix" ]'
      goarch: '[ "ppc64" ]'
      nightly: ${{ contains(github.ref, '-nightly') }}
    secrets:
      DOCKER_TOKEN_COLLECTOR_RELEASES: ${{ secrets.DOCKER_TOKEN_COLLECTOR_RELEASES }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
  release-windows:
    name: Release Core (Windows)
    if: ${{ !contains(github.ref, '-nightly') }}
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol
      goos: '[ "windows" ]'
      goarch: '[ "386", "amd64", "arm64" ]'
      runner_os: windows-2022
    secrets:
      DOCKER_TOKEN_COLLECTOR_RELEASES: ${{ secrets.DOCKER_TOKEN_COLLECTOR_RELEASES }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
