name: Release Core

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Release Core
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol
      goos: '[ "linux", "windows", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x" ]'
      runs-on: 'ubuntu-22.04'
    secrets: inherit
    permissions: write-all
