name: Release Contrib

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Release Contrib
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-contrib-cgo
      goos: '[ "darwin" ]'
      goarch: '[ "amd64", "arm64" ]'
      runs-on: 'macos-latest'
    secrets: inherit
    permissions: write-all
