name: "Close stale issues and pull requests"
on:
  workflow_dispatch:
  schedule:
    - cron: "12 5 * * *" # arbitrary time not to DDOS GitHub

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # required for managing stale issues
      pull-requests: write # required for managing stale PRs
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check rate_limit before
        run: gh api /rate_limit
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR was marked stale due to lack of activity. It will be closed in 14 days.'
          close-pr-message: 'Closed as inactive. Feel free to reopen if this PR is still being worked on.'
          close-issue-message: 'This issue has been closed as inactive because it has been stale for 120 days with no activity.'
          close-issue-label: 'closed as inactive'
          days-before-pr-stale: 14
          days-before-issue-stale: 60
          days-before-pr-close: 14
          days-before-issue-close: 60
          exempt-issue-labels: 'never stale,renovatebot'
          ascending: true
          operations-per-run: 6000
          exempt-pr-labels: 'never stale,renovatebot'
      - name: Check rate_limit after
        run: gh api /rate_limit
